public without sharing class CarCareServiceConstants {
    
    public static Integer defaultWeeks = 2;
    public static Integer defaultRange = 10;
    public static Integer default_pagination_for_Mobile = 2;
    public static Integer default_pagination_for_Laptop = 4 ;
    public static Integer default_pagination_for_Tablet = 4 ;
    public static String Car_Care_Service_Setting = 'Car_Care_Service_Setting';
}