public without sharing class CarCareServiceConstants {
    public static String Appointment_Api_Str ='AppointmentApi';
    public static String Authorization_Key ='AuthorizationKey';
    public static String Store_End_Point ='storeEndPoint';
    public static String Service_End_Point ='serviceEndPoint';
    public static String Vehicle_Make_End_Point ='vehicleMakeEndPoint';
    public static String Vehicle_Model_End_Point ='vehicleModelEndPoint';
    public static String Years_End_Point ='YearsEndPoint';
    public static String Near_By_Range ='NearByRange';
    
}
